# Generated by Django 5.2.9 on 2025-12-03 13:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Veuillez entrer une adresse e-mail valide.')])),
                ('nom_complet', models.CharField(max_length=150, validators=[users.models.validate_nom, django.core.validators.MinLengthValidator(3, message='Le nom complet doit comporter au moins 3 caractères.')])),
                ('role', models.CharField(choices=[('client', 'Client'), ('business_owner', 'Business Owner'), ('nutritionist', 'Nutritionniste'), ('coach', 'Coach'), ('admin', 'Admin')], default='client', max_length=20)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir uniquement des chiffres (8 à 15 caractères).', regex='^[0-9]{8,15}$')])),
                ('ville', models.CharField(blank=True, max_length=100, null=True, validators=[users.models.validate_ville])),
                ('pdp', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sport_type', models.CharField(choices=[('fitness', 'Fitness'), ('yoga', 'Yoga'), ('cardio', 'Cardio'), ('musculation', 'Musculation'), ('crossfit', 'CrossFit')], max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('subscription_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('location', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('certifications', models.TextField(blank=True, help_text='Coach certifications and credentials')),
                ('show_on_website', models.BooleanField(default=True, help_text='Display this coach on the public trainers page')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('office_address', models.CharField(blank=True, max_length=255)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('availability', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('professional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('professional_phone', models.CharField(max_length=20)),
                ('social_media_account', models.CharField(blank=True, max_length=255, null=True)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
