# Generated by Django 5.2.8 on 2025-12-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Latitude of the coach's location.", null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Longitude of the coach's location.", null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='show_map',
            field=models.BooleanField(default=True, help_text="Make the coach's map visible on their profile."),
        ),
    ]
