# Generated by Django 5.2.7 on 2025-10-24 19:28

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Veuillez entrer une adresse e-mail valide.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nom_complet',
            field=models.CharField(max_length=150, validators=[users.models.validate_nom, django.core.validators.MinLengthValidator(3, message='Le nom complet doit comporter au moins 3 caractères.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num_tel',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir uniquement des chiffres (8 à 15 caractères).', regex='^[0-9]{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[users.models.validate_ville]),
        ),
    ]
