# Generated by Django 6.0 on 2025-12-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_blog_options_blog_likes_blog_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='toxicity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='toxicity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
