# Generated by Django 5.2.9 on 2025-12-03 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Supplement', 'Supplement'), ('Equipment', 'Equipment'), ('Snacks', 'Snacks'), ('Protein', 'Protein'), ('Vitamins', 'Vitamins'), ('Organic', 'Organic'), ('Vegan', 'Vegan'), ('Others', 'Others')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
