# Generated by Django 5.2.8 on 2025-11-19 17:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nutritionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sport_type', models.CharField(choices=[('fitness', 'Fitness'), ('yoga', 'Yoga'), ('cardio', 'Cardio'), ('musculation', 'Musculation'), ('crossfit', 'CrossFit')], max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('session_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('subscription_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('location', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('certifications', models.TextField(blank=True, help_text='Coach certifications and credentials')),
                ('show_on_website', models.BooleanField(default=True, help_text='Display this coach on the public trainers page')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
    ]
