# Generated by Django 5.2.8 on 2025-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(choices=[('nutrition', 'Nutrition'), ('fitness', 'Fitness'), ('wellness', 'Santé & Bien-être'), ('consultation', 'Consultation'), ('ia', 'IA & Technologie'), ('products', 'Produits & Lifestyle')], max_length=20),
        ),
    ]
