# Generated by Django 5.2.7 on 2025-11-30 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('untreated', 'Untreated'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='untreated', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mode',
            field=models.CharField(choices=[('face_to_face', 'Face to Face'), ('visio', 'Visio')], default='face_to_face', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
