# Generated by Django 5.2.7 on 2025-11-30 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['coach', 'nutritionist']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
