# Generated by Django 5.2.7 on 2025-11-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_populate_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
