# Generated by Django 5.2.7 on 2025-11-15 19:38

from django.db import migrations

def combine_names(apps, schema_editor):
    Client = apps.get_model('appointments', 'Client')
    for client in Client.objects.all():
        client.nom_complet = f"{client.first_name} {client.last_name}"
        client.save()

def uncombine_names(apps, schema_editor):
    Client = apps.get_model('appointments', 'Client')
    for client in Client.objects.all():
        parts = client.nom_complet.split(' ', 1)
        client.first_name = parts[0]
        client.last_name = parts[1] if len(parts) > 1 else ''
        client.save()

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_client_nom_complet'),
    ]

    operations = [
        migrations.RunPython(combine_names, uncombine_names),
    ]