# Generated by Django 5.2.8 on 2025-11-20 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=100)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('professional_email', models.EmailField(max_length=254, unique=True)),
                ('professional_phone', models.CharField(max_length=20)),
                ('social_media_account', models.CharField(blank=True, max_length=255, null=True)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
    ]
