# Generated by Django 5.2.8 on 2025-11-10 13:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only alphabetic characters are allowed.')])),
                ('theme', models.CharField(choices=[('CS_AI', 'Computer Science & Artificial Intelligence'), ('SE', 'Science & Engineering'), ('SSE', 'Social Sciences & Education'), ('IT', 'Interdisciplinary Themes')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
