# Generated by Django 5.2.8 on 2025-11-20 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_businessowner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Supplement', 'Supplement'), ('Equipment', 'Equipment'), ('Snacks', 'Snacks'), ('Protein', 'Protein'), ('Vitamins', 'Vitamins'), ('Organic', 'Organic'), ('Vegan', 'Vegan'), ('Others', 'Others')], max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.businessowner')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'user')},
            },
        ),
    ]
